# Generated by Django 5.1 on 2024-08-27 13:54

import apps.technologies.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('deleted_date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='technologies/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.technologies.models.validateImageSize], verbose_name='Image')),
                ('stars', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologys',
            },
        ),
    ]
