# Generated by Django 5.1 on 2024-08-27 13:54

import apps.projects.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('deleted_date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.projects.models.validateImageSize], verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('frontend', models.URLField(blank=True, null=True, verbose_name='Frontend')),
                ('backend', models.URLField(blank=True, null=True, verbose_name='Backend')),
                ('technologies', models.ManyToManyField(to='technologies.technology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
